<?php
/**
 * Locale data for 'zh_CN'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return CMap::mergeArray(
	require(Yii::getPathOfAlias('system.i18n.data').DIRECTORY_SEPARATOR.basename(__FILE__)),
	array(
	  'languages' => 
		  array (
		  	 'zh_cn' => '中文',
		  	 'en_us' => '英文',
		  	 'zh' => '中文',
		  	 'en' => '英文'
		  )
	)
);
